kind: List
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: cart-service
      name: cart-service
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: cart-service
        deploymentconfig: cart-service
      sessionAffinity: None
      type: ClusterIP