apiVersion: v1
kind: PersistentVolume
metadata:
  name: coolstore-postgres
  labels:
    app: coolstore-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/coolstore/data
    server: 10.87.1.191
persistentVolumeReclaimPolicy: Recycle
