apiVersion: v1
kind: PersistentVolume
metadata:
  name: coolstore-postgres-pv0001
  labels:
    app: inventory-service
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/coolstore/data/inventory
    server: 10.87.1.191
persistentVolumeReclaimPolicy: Recycle
