apiVersion: v1
kind: PersistentVolume
metadata:
  name: collstore-postgres-pv0001
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/coolstore/data/inventory
    server: 10.87.1.191
persistentVolumeReclaimPolicy: Retain
