apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-coolstore-postgres-pvc
  labels:
    app: coolstore-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: coolstore-postgres
  storageClassName: ""